version: '2'

services:
  mqtt-status:
    container_name: mqtt-status
    image: mqtt-device-status
    build: image
    restart: unless-stopped
    environment:
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - MQTT_TOPIC=${MQTT_TOPIC}
      - MQTT_BROKER=${MQTT_BROKER}
      - PYTHONUNBUFFERED=1
